name: alzheimer-project
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.7
  - torchvision>=0.8
  - cudatoolkit=11.1
  - numpy
  - scikit-learn
  - tqdm
  - matplotlib
  - opencv
  - nibabel
  - pip:
      - SimpleITK
